server:
    port: 8088
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        #下面使用的docker部署时候就用容器名作为ip
        #url: jdbc:mysql://mysql:3306/mysql?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: jgg271934
        #url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        #username: root
        #password: 123456
        thymeleaf:
        cache: false
mybatis:
    mapper-locations: classpath*:mybatis/mapper/*/*.xml

#在控制台打印MySQL日志
logging:
    level:
        com:
            core:
                blog:
                    mapper: debug
                console:
                    mapper: debug
#logging.level.自己的mapper包=日志级别

wzurl: https://www.douyu.com/g_wzry
lolurl: https://www.douyu.com/g_LOL
lsurl: https://www.douyu.com/g_How
mailsmtpauth: true
mailtransportprotocol: smtp
mailsendcharset: UTF-8
mailsmtpport: 465
mailisssl: true
mailhost: smtp.163.com
mailauthname: zhangwforever@163.com
mailauthpassword: 1q2w3e4r
mailsmtptimeout: 10000
dingDingRobotUrl: https://oapi.dingtalk.com/robot/send?access_token=31fa0a0c2d423b61abc6f150920605ab5ad2de20e694c071b82cf4dbd937d3f8
telphone1: 18829288843
telphone2: 18729086497

